name: Increment Counter

on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write # Grant permission to push changes

jobs:
  increment-counter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Make script executable
        run: chmod +x increment_counter.sh

      - name: Run increment script
        run: ./increment_counter.sh

      - name: Push changes
        run: |
          git push
